[theme]
primaryColor = "#2A81BF"
blueColor = "#2A81BF"
borderColor = "#7EB3D8"
showWidgetBorder = true
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262626"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "info"

[server]
port = 8501
headless = true
runOnSave = true
